---
# tasks file for Dell-Networking.dellos-aaa
 - name: "Provisioning AAA configuration for dellos9"
   dellos9_config:
      src: dellos9_aaa.j2
      provider: "{{ cli }}"
   when: ansible_net_os_name == "dellos9"
#   notify: save config os9
   register: output

